Repository osam-cologne/archlinux-proaudio, pull requests merged in 2022-06, with the labels that each got.

#68 package paulxstretch
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/paulxstretch/PKGBUILD
  packages/paulxstretch/fix-gcc12.patch
Labels: package

#69 package faustlive
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/faustlive/PKGBUILD
Labels: package

#65 Automatically push selected packages to AUR
  .drone.yml
  .gitignore
  aur/.ssh/config
  aur/.ssh/known_hosts
  aur/README.md
  aur/gitignore-base
  aur/packages
  packages/aether.lv2/PKGBUILD
  packages/glasscoder/PKGBUILD
  packages/hpklinux/PKGBUILD
  packages/klick/PKGBUILD
  packages/kpp/PKGBUILD
  packages/ola/PKGBUILD
  packages/paulxstretch/PKGBUILD
  packages/rakarrack-plus/PKGBUILD
  packages/rtcqs/PKGBUILD
  packages/swh-plugins.lv2/PKGBUILD
  packages/vcf-lv2/PKGBUILD
  tools/build-env.sh
  tools/prepare-build.sh
  tools/push-aur.sh
Labels: tooling

#71 package clap
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/clap/PKGBUILD
Labels: package

#75 update paulxstretch to 1.6.0
  nvchecker/old_ver.json
  packages/paulxstretch/PKGBUILD
  packages/paulxstretch/fix-gcc12.patch
Labels: update

#74 ola: fix stdc++ assertions crashing olad
  packages/ola/PKGBUILD
Labels: bug

#72 patch vcvrack to build for aarch64
  packages/clap/PKGBUILD
  packages/ola/PKGBUILD
  packages/vcvrack/PKGBUILD
  packages/vcvrack/aarch64.patch
  packages/vcvrack/trademark.eml
Labels: enhancement

#77 patch ola to fix crash and tests
  packages/ola/.gitignore
  packages/ola/PKGBUILD
Labels: bug

#78 update glasscoder to 2.0.1
  nvchecker/old_ver.json
  packages/glasscoder/PKGBUILD
Labels: update

#80 feat: add new script for nvchecker notification to Matrix chat
  nvchecker/README.md
  nvchecker/nvchecker-notify-matrixchat.json.tmpl
  nvchecker/nvchecker-notify-matrixchat.py
  nvchecker/run-nvchecker.cron
Labels: enhancement, tooling
