Repository osam-cologne/archlinux-proaudio, pull requests merged in 2022-12, with the labels that each got.

#161 update clap to v1.1.3
  nvchecker/old_ver.json
  packages/clap/PKGBUILD
Labels: update

#166 update vcvrack to v2.2.1
  nvchecker/old_ver.json
  packages/vcvrack/PKGBUILD
  packages/vcvrack/aarch64.patch
Labels: update

#167 feat: update abcmidi to version 2022.12.07
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#169 feat: update package abcmidi to version 2022.12.09
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#162 Package uhhyou-plugins
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/uhhyou-plugins/PKGBUILD
Labels: package

#170 feat: update package 'abcm2ps' to version 8.14.14
  nvchecker/old_ver.json
  packages/abcm2ps/PKGBUILD
Labels: update

#171 feat: update package 'uhhyou-plugins' to upstream version 0.50.0
  nvchecker/old_ver.json
  packages/uhhyou-plugins/PKGBUILD
Labels: update

#172 feat: update package 'faustlive' to upstream version 2.5.13
  nvchecker/old_ver.json
  packages/faustlive/PKGBUILD
Labels: update

#173 feat: update package 'abcmidi' to upstream version 2022.12.22
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#174 feat: update package 'octasine' to upstream version 0.8.2
  nvchecker/old_ver.json
  packages/octasine/PKGBUILD
Labels: update

#175 package clap-validator
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/clap-validator/PKGBUILD
Labels: package

#179 abcmidi: update to v2022.12.27
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#180 uhhyou-plugins: update to v0.51.0
  nvchecker/old_ver.json
  packages/uhhyou-plugins/PKGBUILD
Labels: update

#177 vcvrack: upgrade to v2.2.2
  nvchecker/old_ver.json
  packages/vcvrack/.install
  packages/vcvrack/PKGBUILD
  packages/vcvrack/plugins.patch
Labels: bug, update

#181 feat: update package 'abcmidi' to version 2022.12.30
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update
