Repository osam-cologne/archlinux-proaudio, pull requests merged in 2022-07, with the labels that each got.

#82 update faustlive to 2.5.11
  nvchecker/old_ver.json
  packages/faustlive/PKGBUILD
Labels: update

#83 package ninjamsrv
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/ninjam-server/PKGBUILD
  packages/ninjam-server/ninjam.service
  packages/ninjam-server/ninjam.sysusers
Labels: package

#87 fix: nvchecker config and cron script
  nvchecker/archlinux-proaudio.toml
  nvchecker/run-nvchecker.cron
Labels: bug

#88 docs: add instructions to add keyfile.toml to nvchecker readme
  nvchecker/README.md
Labels: documentation

#70 build debug packages
  .drone.yml
  .gitignore
  README.md
  packages/faustlive/PKGBUILD
  packages/vcf-lv2/PKGBUILD
  tools/build-env.sh
  tools/makepkg.conf
  tools/pacman.conf
  tools/prepare-build.sh
Labels: tooling

#89 bump some pkgrels to trigger AUR updates and debug builds
  packages/abcm2ps/PKGBUILD
  packages/jack-matchmaker/PKGBUILD
  packages/jalv-select/PKGBUILD
  packages/mamba/PKGBUILD
  packages/mclk.lv2/PKGBUILD
  packages/midiomatic/PKGBUILD
  packages/python-pyjacklib/PKGBUILD
  packages/python-rtmidi/PKGBUILD
  packages/qjackcapture/PKGBUILD
  packages/stone-phaser/PKGBUILD
  packages/string-machine/PKGBUILD
  packages/ykchorus/PKGBUILD
Labels: enhancement

#90 feat: add package elephantdsp-roomreverb
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/elephantdsp-roomreverb/PKGBUILD
  packages/elephantdsp-roomreverb/roomreverb-devendor_juce.patch
Labels: package

#92 fix aur commit author
  tools/build-env.sh
Labels: bug, tooling

#93 fix building single package
  tools/prepare-build.sh
Labels: bug, tooling

#94 package gsjackctl
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/gnome-shell-extension-gsjackctl/PKGBUILD
Labels: package

#95 feat: update elephantdsp-roomreverb to version 0.6.1
  nvchecker/old_ver.json
  packages/elephantdsp-roomreverb/PKGBUILD
Labels: package, update

#99 vcvrack: add objcopy rule for aarch64
  packages/vcvrack/PKGBUILD
  packages/vcvrack/aarch64.patch
Labels: bug

#98 ola: fix patch source
  packages/ola/PKGBUILD
Labels: bug

#100 Update CLAP to 1.1.1
  nvchecker/old_ver.json
  packages/clap/PKGBUILD
Labels: package, update

#96 Package some first vcvrack plugins
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/vcvrack-ahornberg/.gitignore
  packages/vcvrack-ahornberg/PKGBUILD
  packages/vcvrack-sonusmodular/PKGBUILD
  packages/vcvrack-zetacarinae/PKGBUILD
Labels: package

#102 update vcvrack-fundamental to v2.3.0
  packages/vcvrack/PKGBUILD
  packages/vcvrack/plugins.patch
Labels: update

#103 update gsjackctl to v2
  nvchecker/old_ver.json
  packages/gnome-shell-extension-gsjackctl/PKGBUILD
Labels: update

#104 update python-pysimplegui to 4.60.3
  nvchecker/old_ver.json
  packages/python-pysimplegui/PKGBUILD
Labels: update

#84 update jamulus to 3.9.0
  nvchecker/old_ver.json
  packages/jamulus/PKGBUILD
Labels: update
