Repository osam-cologne/archlinux-proaudio, pull requests merged in 2022-05, with the labels that each got.

#55 Package rakarrack-plus
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/rakarrack-plus/.gitignore
  packages/rakarrack-plus/PKGBUILD
Labels: package

#51 package glasscoder
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/glasscoder/PKGBUILD
Labels: package

#58 Remove pro-audio group from jamulus-headless
  packages/jamulus/PKGBUILD
Labels: bug

#59 update rakarrack-plus to 1.2.1
  nvchecker/old_ver.json
  packages/rakarrack-plus/.gitignore
  packages/rakarrack-plus/PKGBUILD
Labels: update

#61 feat: bump pkgrel due to protobuf soname bump
  packages/ola/PKGBUILD
Labels: enhancement

#62 package rtcqs
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/rtcqs/.gitignore
  packages/rtcqs/PKGBUILD
Labels: package

#63 package PySimpleGUI
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/python-pysimplegui/PKGBUILD
Labels: package

#64 update vcvrack to 2.1.1
  nvchecker/old_ver.json
  packages/vcvrack/PKGBUILD
Labels: update

#67 update python-pysimplegui to 4.60.1
  nvchecker/old_ver.json
  packages/python-pysimplegui/PKGBUILD
Labels: update
