Repository osam-cologne/archlinux-proaudio, pull requests merged in 2022-09, with the labels that each got.

#111 surge-xt: fix crash
  packages/surge-xt/.gitignore
  packages/surge-xt/PKGBUILD
Labels: bug

#114 update rakarrack-plus to 1.2.3
  nvchecker/old_ver.json
  packages/rakarrack-plus/PKGBUILD
Labels: update

#121 feat: import package python-midi from AUR
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/python-mido/PKGBUILD
Labels: package
