Repository osam-cologne/archlinux-proaudio, pull requests merged in 2023-01, with the labels that each got.

#182 package liblc3
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/liblc3/.gitignore
  packages/liblc3/PKGBUILD
Labels: package

#176 package clap-example-host
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/clap-example-host/.gitignore
  packages/clap-example-host/PKGBUILD
Labels: package

#184 feat: update package abcmidi to version 2023.01.05
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#183 clap-example-host: update to v1.0.3
  nvchecker/old_ver.json
  packages/clap-example-host/.gitignore
  packages/clap-example-host/PKGBUILD
Labels: update

#185 feat: update package abcmidi to version 2023.01.06
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#186 feat: update package abcmidi to version 2023.01.08
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#187 feat: update package abcmidi to version 2023.01.10
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#188 clap-validator: update to v0.2.0
  nvchecker/old_ver.json
  packages/clap-validator/PKGBUILD
Labels: update

#189 vcvrack-sonusmodular: update to v2.1.0
  nvchecker/old_ver.json
  packages/vcvrack-sonusmodular/PKGBUILD
Labels: update

#190 feat: update package 'elephantdsp-roomreverb' to version 1.0.0
  nvchecker/old_ver.json
  packages/elephantdsp-roomreverb/PKGBUILD
Labels: update

#191 fix: bump pkgrel of python-soundfile to trigger rebuild
  packages/python-soundfile/PKGBUILD
Labels: bug, update

#193 vcvrack: update to v2.2.3
  nvchecker/old_ver.json
  packages/vcvrack/PKGBUILD
Labels: update

#194 uhhyou-plugins: update to v0.51.1
  nvchecker/old_ver.json
  packages/uhhyou-plugins/PKGBUILD
Labels: update

#195 uhhyou-plugins: update to v0.52.0
  nvchecker/old_ver.json
  packages/uhhyou-plugins/PKGBUILD
Labels: update
