Repository osam-cologne/archlinux-proaudio, pull requests merged in 2023-12, with the labels that each got.

#317 fix: bump pkgrel to trigegr rebuild of clap-example-host
  packages/clap-example-host/PKGBUILD
Labels: bug, update

#318 feat: update package 'uhhyou-plugins' to 0.59.0-1
  nvchecker/old_ver.json
  packages/uhhyou-plugins/PKGBUILD
Labels: update

#320 feat: update package raysession to 0.14.3-1
  nvchecker/old_ver.json
  packages/raysession/PKGBUILD
Labels: update

#323 feat: update package 'airwindows-lv2' to 26.0-1
  nvchecker/old_ver.json
  packages/airwindows-lv2/PKGBUILD
Labels: update

#324 CI: check git diff to ignore unchanged packages
  tools/build-env.sh
  tools/prepare-build.sh
Labels: tooling

#325 vcvrack-alefsbits: update to v2.5.54
  nvchecker/old_ver.json
  packages/vcvrack-alefsbits/PKGBUILD
Labels: update

#328 Fix package list
  .drone.yml
  tools/gen-packagelist.sh
  tools/prepare-build.sh
  tools/update-db.sh
Labels: tooling

#326 seq66: update to v0.99.11
  nvchecker/old_ver.json
  packages/seq66/PKGBUILD
Labels: update

#327 airwindows-lv2: update to v26.2
  nvchecker/old_ver.json
  packages/airwindows-lv2/PKGBUILD
Labels: update

#331 feat: update package 'python-mido' to 1.3.1-1
  nvchecker/old_ver.json
  packages/python-mido/PKGBUILD
Labels: update

#332 Package abseil-cpp11
  aur/packages
  packages/abseil-cpp11/PKGBUILD
Labels: package

#330 Package protobuf-21
  aur/packages
  packages/protobuf-21/.gitignore
  packages/protobuf-21/PKGBUILD
Labels: package

#334 python-mido: update to v1.3.2
  packages/python-mido/PKGBUILD
Labels: update

#335 abcmidi: update to v2023.12.17
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#337 feat: update package 'abcmidi' to 2023.12.23-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#340 feat: update package 'uhhyou-plugins' to 0.61.0-1
  nvchecker/old_ver.json
  packages/uhhyou-plugins/PKGBUILD
Labels: update

#341 feat: update package 'abcmidi' to 2023.12.28-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update
