Repository osam-cologne/archlinux-proaudio, pull requests merged in 2023-02, with the labels that each got.

#178 Respecting freedesktop spec for svg icons
  packages/jamulus/PKGBUILD
Labels: bug

#196 feat: update package 'abcmidi' to version 2023.02.07
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#197 clap-validator: update to v0.3.0
  nvchecker/old_ver.json
  packages/clap-validator/PKGBUILD
Labels: update

#199 feat: update package 'abcmidi' to version 2023.02.08
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#200 feat: update package 'octasine' to version 0.8.3-1
  nvchecker/old_ver.json
  packages/octasine/PKGBUILD
Labels: update

#201 feat: update package 'python-soundfile' to version 0.12.0-1
  nvchecker/old_ver.json
  packages/python-soundfile/PKGBUILD
Labels: update

#202 feat: update package 'python-soundfile' to version 0.12.1-1
  nvchecker/old_ver.json
  packages/python-soundfile/PKGBUILD
Labels: update

#203 fix: don't include CLAP plugin on aarch64 for now
  packages/octasine/PKGBUILD
Labels: bug

#204 fix: enable tests on aarch64 again
  packages/octasine/PKGBUILD
Labels: bug

#28 package lpd8editor
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/lpd8editor/PKGBUILD
Labels: package

#205 feat: update package 'abcmidi' to version 2023.02.20-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#207 ola: update to v0.10.9
  nvchecker/old_ver.json
  packages/ola/.gitignore
  packages/ola/PKGBUILD
Labels: update
