Repository osam-cologne/archlinux-proaudio, pull requests merged in 2023-09, with the labels that each got.

#271 feat: update package abcmidi to 2023.08.31-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#270 [mamba] fix: backport asprintf compilation error fix
  packages/mamba/PKGBUILD
  packages/mamba/mamba-asprintf-7eb70bf.patch
Labels: bug

#269 feat: add package seq66
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/seq66/PKGBUILD
  packages/seq66/seq66-docdir.patch
Labels: package

#273 feat: update package abcmidi to 2023.09.06-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#274 feat: update package abcmidi to 2023.09.11-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#264 feat: update package vcvrack to version 2.4.1-1
  nvchecker/old_ver.json
  packages/vcvrack/.gitignore
  packages/vcvrack/PKGBUILD
Labels: update

#276 feat: update package raysession to 0.14.0-1
  nvchecker/old_ver.json
  packages/raysession/PKGBUILD
  packages/raysession/raysession-makefile-destdir.patch
Labels: update

#277 vcvrack-alliewayaudio-freebies: update to v2.0.7
  nvchecker/old_ver.json
  packages/vcvrack-alliewayaudio-freebies/PKGBUILD
Labels: update

#278 feat: update package raysession to 0.14.1-1
  nvchecker/old_ver.json
  packages/raysession/PKGBUILD
Labels: update

#279 feat: update package convertwithmoss to 7.0.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#280 seq66: update to v0.99.9
  nvchecker/old_ver.json
  packages/seq66/PKGBUILD
Labels: update
