Repository osam-cologne/archlinux-proaudio, pull requests merged in 2023-04, with the labels that each got.

#218 feat: update package 'octasine' to version 0.8.4-1
  nvchecker/old_ver.json
  packages/octasine/PKGBUILD
Labels: update

#219 fix: 'qt-base' does not provide soname dependencies
  packages/lpd8editor/PKGBUILD
Labels: bug

#220 feat: update package 'octasine' to version 0.8.5-1
  nvchecker/old_ver.json
  packages/octasine/PKGBUILD
Labels: update

#214 feat: add new package 'convertwithmoss'
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: package

#221 feat: update package 'octasine' to version 0.8.6-1
  nvchecker/old_ver.json
  packages/octasine/PKGBUILD
Labels: update

#223 hpklinux: update to v4.20.39
  nvchecker/old_ver.json
  packages/hpklinux/PKGBUILD
Labels: update
