Repository osam-cologne/archlinux-proaudio, pull requests merged in 2023-11, with the labels that each got.

#299 vcvrack-alefsbits: update to v2.5.51
  nvchecker/old_ver.json
  packages/vcvrack-alefsbits/PKGBUILD
Labels: update

#301 feat: update package abcmidi to 2023.11.08-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#300 feat: add new package 'ot-cryptid'
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/ot-cryptid/PKGBUILD
Labels: package

#298 hpklinux: update to v4.20.42
  nvchecker/old_ver.json
  packages/hpklinux/PKGBUILD
  packages/hpklinux/python.patch
Labels: update

#302 feat: update package convertwithmoss to 7.3.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#303 vcvrack-alefsbits: update to v2.5.52
  nvchecker/old_ver.json
  packages/vcvrack-alefsbits/PKGBUILD
Labels: update

#304 feat: update package abcmidi to 2023.11.14-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#306 feat: update package abcmidi to 2023.11.17-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#307 feat: update package abcmidi to 2023.11.26-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#310 feat: add new package 'metaltone.lv2'
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/metaltone.lv2/.gitignore
  packages/metaltone.lv2/PKGBUILD
Labels: package

#309 feat: add new package 'collisiondrive.lv2'
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/collisiondrive.lv2/PKGBUILD
Labels: package

#308 feat: add new package 'airwindows-lv2'
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/airwindows-lv2/PKGBUILD
Labels: package

#313 feat: update package tonetwistplugs to 0.7-1
  nvchecker/old_ver.json
  packages/tonetwistplugs/PKGBUILD
Labels: update

#314 fix: build errors and dependencies in pkg string-machine
  packages/string-machine/PKGBUILD
  packages/string-machine/fix-missing-stdint-include.patch
Labels: bug

#315 fix: build errors in package fluida.lv2
  packages/fluida.lv2/.gitignore
  packages/fluida.lv2/PKGBUILD
  packages/fluida.lv2/fluida-fix-asprintf.patch
Labels: bug
