Repository osam-cologne/archlinux-proaudio, pull requests merged in 2023-06, with the labels that each got.

#246 fix: disable aarch64 format for package simplescreenrecorder
  packages/simplescreenrecorder/PKGBUILD
Labels: bug

#244 feat: update package convertwithmoss to 6.2.1-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#243 uhhyou-plugins: update to v0.56.0, fix for vst3sdk 3.7.8
  nvchecker/old_ver.json
  packages/uhhyou-plugins/PKGBUILD
Labels: update

#247 fix: adapt for changing moduleinfo.json path between vst3sdk versions
  packages/uhhyou-plugins/PKGBUILD
Labels: bug

#248 [simplescreenrecorder] fix: Make source tarball name unique
  packages/simplescreenrecorder/PKGBUILD
Labels: enhancement

#249 feat: update package abcmidi to 2023.06.25-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#250 feat: update package jack-matchmaker to 0.11.0-1
  nvchecker/old_ver.json
  packages/jack-matchmaker/PKGBUILD
Labels: update
