Repository osam-cologne/archlinux-proaudio, pull requests merged in 2024-02, with the labels that each got.

#356 hpklinux: update to v4.20.43
  nvchecker/old_ver.json
  packages/hpklinux/PKGBUILD
Labels: update

#355 paulxstretch: update patch checksum
  packages/paulxstretch/PKGBUILD
Labels: bug

#358 feat: update package 'abcmidi' to 2024.02.07-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#359 fix: use proper pacman update commands in readme examples
  README.md
Labels: bug, documentation

#360 jamulus: bump pkgrel to use latest qt
  packages/jamulus/PKGBUILD
Labels: bug

#361 feat: update package 'abcmidi' to 2024.02.11-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#362 feat: update package 'abcmidi' to 2024.02.14-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#363 feat: update package 'covertwithmoss' to 7.4.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#365 paulxstretch: fix patch sha256sum
  packages/paulxstretch/PKGBUILD
  packages/simplescreenrecorder/.gitignore
Labels: bug

#366 feat: update package 'abcmidi' to 2024.02.19-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#367 feat: update package 'audiowmark' to 0.6.2-1
  nvchecker/old_ver.json
  packages/audiowmark/PKGBUILD
Labels: update

#368 feat: update package 'abcmidi' to 2024.02.22-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#369 feat: update package 'abcmidi' to 2024.02.23-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#371 Fix clap-example-host and vcvrack for rtmidi 6
  packages/clap-example-host/PKGBUILD
  packages/vcvrack/PKGBUILD
Labels: bug

#372 feat: update package 'abcmidi' to 2024.02.25-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#373 feat: update package 'rtcqs' to 0.5.5-1
  nvchecker/old_ver.json
  packages/rtcqs/.gitignore
  packages/rtcqs/PKGBUILD
Labels: update
