Repository osam-cologne/archlinux-proaudio, pull requests merged in 2024-01, with the labels that each got.

#342 feat: update package 'abcmidi' to 2024.01.02-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#343 feat: update package 'abcm2ps' to 8.14.15-1
  nvchecker/old_ver.json
  packages/abcm2ps/PKGBUILD
Labels: update

#344 feat: update package 'fluida.lv' to 0.9-1
  nvchecker/old_ver.json
  packages/fluida.lv2/.gitignore
  packages/fluida.lv2/PKGBUILD
  packages/fluida.lv2/fluida-fix-asprintf.patch
  packages/fluida.lv2/lv2ui.version
Labels: bug, update

#345 feat: update package 'linux-show-player' to 0.6-1
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/linux-show-player/PKGBUILD
Labels: bug, update

#348 fix: update URL in nvchecker config for dxconvert
  nvchecker/archlinux-proaudio.toml
Labels: bug

#349 fix: re-add dependency on 'gst-plugins-good' (removed in error)
  packages/linux-show-player/PKGBUILD
Labels: bug

#346 faustlive: update to v2.5.17
  nvchecker/old_ver.json
  packages/faustlive/PKGBUILD
Labels: update

#351 feat: update package 'fluida.lv2' to 0.9.2-1
  nvchecker/old_ver.json
  packages/fluida.lv2/PKGBUILD
Labels: update

#352 feat: update package 'seq66' to 0.99.12-1
  nvchecker/old_ver.json
  packages/seq66/PKGBUILD
Labels: update

#353 feat: update package 'abcmidi' to 2024.01.15-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update
