Repository osam-cologne/archlinux-proaudio, pull requests merged in 2024-03, with the labels that each got.

#374 feat: update package 'linux-show-player' to 0.6.1-1
  nvchecker/old_ver.json
  packages/linux-show-player/PKGBUILD
Labels: update

#375 feat: update package 'rtcqs' to 0.6.0-1
  nvchecker/old_ver.json
  packages/rtcqs/PKGBUILD
Labels: update

#376 feat: update package 'abcmidi' to 2024.03.02-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#377 feat: update package 'rtcqs' to 0.6.1-1
  nvchecker/old_ver.json
  packages/rtcqs/PKGBUILD
Labels: update

#378 feat: update package 'rtcqs' to 0.6.2-1
  nvchecker/old_ver.json
  packages/rtcqs/PKGBUILD
Labels: update

#379 feat: update package 'airwindows-lv2' to 28.0-1
  nvchecker/old_ver.json
  packages/airwindows-lv2/PKGBUILD
Labels: update

#380 vcvrack: use new glfw package
  packages/vcvrack/PKGBUILD
Labels: enhancement

#382 feat: update package 'linux-show-player' to 0.6.2-1
  nvchecker/old_ver.json
  packages/linux-show-player/PKGBUILD
Labels: update

#383 feat: update package 'covertwithmoss' to 7.5.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#385 feat: update package 'abcmidi' to 2024.03.13-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#386 fix: remove nvchecker config for python-pysimplegui
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
Labels: bug

#387 feat: update package 'abcmidi' to 2024.03.18-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#388 feat: update package 'abcmidi' to 2024.03.19-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#390 feat: update package 'abcmidi' to 2024.03.21-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#391 feat: update package 'mamba' to 2.6-1
  nvchecker/old_ver.json
  packages/mamba/PKGBUILD
  packages/mamba/mamba-asprintf-7eb70bf.patch
Labels: update

#393 feat: add 'airwindows.lv2' package to AUR
  aur/packages
  packages/airwindows-lv2/PKGBUILD
Labels: enhancement

#394 feat: add 'airwindows-lv2' package to AUR (2nd try)
  aur/packages
  packages/airwindows-lv2/PKGBUILD
Labels: enhancement

#397 seq66: liblo 0.32 compatibility
  packages/seq66/.gitignore
  packages/seq66/PKGBUILD
Labels: bug
