Repository osam-cologne/archlinux-proaudio, pull requests merged in 2024-07, with the labels that each got.

#443 feat: update package 'convertwithmoss' to 10.2.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#444 octasine: update to v0.9.1
  nvchecker/old_ver.json
  packages/octasine/PKGBUILD
Labels: update

#447 feat: update package ratatouille.lv2 to 0.5-1
  nvchecker/old_ver.json
  packages/ratatouille.lv2/PKGBUILD
Labels: update

#450 feat: update package ratatouille.lv2 to 0.6-1
  nvchecker/old_ver.json
  packages/ratatouille.lv2/PKGBUILD
Labels: update

#451 feat: add package 'ot-simian1' (legacy version 1)
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/ot-simian1/PKGBUILD
  packages/ot-simian1/dub.json
  packages/ot-simian1/generate-manifest-ttl.py
Labels: package

#452 feat: update package ratatouille.lv2 to 0.7-1
  nvchecker/old_ver.json
  packages/ratatouille.lv2/PKGBUILD
Labels: update

#453 feat: remove package python-pysimplegui
  packages/python-pysimplegui/PKGBUILD
  packages/rtcqs/PKGBUILD
Labels: removal

#455 feat: update package abcmidi to 2024.07.26-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update
