Repository osam-cologne/archlinux-proaudio, pull requests merged in 2024-04, with the labels that each got.

#399 Package midi2-workbench
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/midi2-workbench/PKGBUILD
  packages/midi2-workbench/midi2-workbench.desktop
  packages/midi2-workbench/midi2-workbench.sh
Labels: package

#401 faustlive: update to v2.5.18
  .drone.yml
  nvchecker/old_ver.json
  packages/faustlive/PKGBUILD
Labels: update

#402 feat: update package 'convertwithmoss' to 8.0.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#403 feat: update package 'linux-show-player' to 0.6.3-1
  nvchecker/old_ver.json
  packages/linux-show-player/PKGBUILD
Labels: update

#404 vcvrack: update to v2.5.0
  nvchecker/old_ver.json
  packages/vcvrack/PKGBUILD
Labels: update

#406 feat: bump pkgrel of 'convertwithmoss' to 2 to trigger sync to AUR
  aur/packages
  packages/convertwithmoss/PKGBUILD
Labels: update

#407 vcvrack: update to v2.5.1
  nvchecker/old_ver.json
  packages/vcvrack/PKGBUILD
Labels: update

#409 feat: update package 'convertwithmoss' to 8.5.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#411 convertwithmoss: update to v8.5.1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
  packages/convertwithmoss/convertwithmoss.sh
Labels: update

#412 feat: update package 'ykchorus' to 0.2.4-1
  nvchecker/old_ver.json
  packages/ykchorus/PKGBUILD
Labels: update

#414 fix: more 'ykchorus' package fixes
  packages/ykchorus/PKGBUILD
Labels: bug
