Repository osam-cologne/archlinux-proaudio, pull requests merged in 2024-12, with the labels that each got.

#500 feat: update package convertwithmoss to 11.4.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#501 feat: update package seq66 to 0.99.16-1
  nvchecker/old_ver.json
  packages/seq66/PKGBUILD
Labels: update

#502 feat: update package abcmidi to 2024.12.06-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#503 Remove python-soundfile (now in extra)
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/python-soundfile/PKGBUILD
Labels: removal

#504 feat: update package convertwithmoss to 11.5.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#505 feat: update package dxconvert to 3.2.3-1
  nvchecker/old_ver.json
  packages/dxconvert/PKGBUILD
Labels: update

#506 feat: update package abcmidi to 2024.12.16-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#507 feat: update package ratatouille.lv2 to 0.9.4-1
  nvchecker/old_ver.json
  packages/ratatouille.lv2/PKGBUILD
Labels: update

#508 feat: update package abcmidi to 2024.12.22-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#509 [raysession] fix: remove unused cgitb import, incompatible with Pyton >= 3.13
  packages/raysession/PKGBUILD
Labels: bug

#513 feat: update package convertwithmoss to 11.6.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update
