Repository osam-cologne/archlinux-proaudio, pull requests merged in 2025-02, with the labels that each got.

#529 feat: update package convertwithmoss to 12.1.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#530 feat: update package seq66 to 0.99.18-1
  nvchecker/old_ver.json
  packages/seq66/PKGBUILD
Labels: update

#531 fix: trigger rebuilds for Python 3.13 - round #1
  packages/dxconvert/PKGBUILD
  packages/hpklinux/PKGBUILD
  packages/jack-matchmaker/PKGBUILD
  packages/linux-show-player/PKGBUILD
  packages/python-miditk-smf/PKGBUILD
  packages/python-mido/PKGBUILD
  packages/python-pyjacklib/PKGBUILD
  packages/raysession/PKGBUILD
  packages/rtcqs/PKGBUILD
  packages/sfzlint/PKGBUILD
Labels: update

#532 fix: bump qjackcapture pkgrel to trigger Python 3.13 rebuild
  packages/qjackcapture/PKGBUILD
Labels: update

#533 nvchecker cronjob: ignore empty git stash
  nvchecker/run-nvchecker.cron
Labels: bug

#535 vcvrack: vendor libsamplerate
  packages/vcvrack/PKGBUILD
Labels: bug

#526 Basic PKGBUILD templates
  templates/cmake.PKGBUILD
  templates/empty.PKGBUILD
  templates/vcvrack-plugin.PKGBUILD
  tools/README.md
Labels: enhancement

#536 vcvrack: avoid log warnings under Wayland
  packages/vcvrack/PKGBUILD
  packages/vcvrack/wayland.patch
Labels: bug

#539 feat: update neural-amp-modeler-lv2 to 0.1.7-1
  packages/neural-amp-modeler-lv2/PKGBUILD
Labels: update

#540 ratatouille.lv2: update to v0.9.7
  packages/ratatouille.lv2/PKGBUILD
Labels: update

#542 [ratatouille.lv2] fix: ensure that everything is built with GCC
  packages/ratatouille.lv2/PKGBUILD
Labels: bug

#537 vcvrack: integrate custom MIME type for patches, statically link libc++
  packages/vcvrack/PKGBUILD
  packages/vcvrack/vcvrack.desktop
  packages/vcvrack/vcvrack.xml
Labels: enhancement

#538 Package more VCV Rack plugins
  aur/packages
  packages/vcvrack-as/.gitignore
  packages/vcvrack-as/.nvchecker.toml
  packages/vcvrack-as/PKGBUILD
  packages/vcvrack-auraaudio/.gitignore
  packages/vcvrack-auraaudio/.nvchecker.toml
  packages/vcvrack-auraaudio/PKGBUILD
  packages/vcvrack-autinn/.gitignore
  packages/vcvrack-autinn/.nvchecker.toml
  packages/vcvrack-autinn/PKGBUILD
  packages/vcvrack-lilacloop/.gitignore
  packages/vcvrack-lilacloop/.nvchecker.toml
  packages/vcvrack-lilacloop/PKGBUILD
  packages/vcvrack-modllz/.gitignore
  packages/vcvrack-modllz/.nvchecker.toml
  packages/vcvrack-modllz/PKGBUILD
  packages/vcvrack-mschack/.gitignore
  packages/vcvrack-mschack/.nvchecker.toml
  packages/vcvrack-mschack/PKGBUILD
  packages/vcvrack-sha-bang-modules/.gitignore
  packages/vcvrack-sha-bang-modules/.nvchecker.toml
  packages/vcvrack-sha-bang-modules/PKGBUILD
Labels: package

#546 vcvrack: refactor PKGBUILD
  packages/vcvrack/.gitignore
  packages/vcvrack/PKGBUILD
  packages/vcvrack/plugins.patch
Labels: enhancement

#545 feat: add new package 'guitarix.vst'
  .drone.yml
  aur/packages
  packages/guitarix.vst/.nvchecker.toml
  packages/guitarix.vst/PKGBUILD
  tools/makepkg.conf
Labels: package

#548 guitarix.vst: fix dependencies
  packages/guitarix.vst/PKGBUILD
Labels: bug

#549 More vcvrack plugins
  packages/vcvrack-chemical-elements/.gitignore
  packages/vcvrack-chemical-elements/.nvchecker.toml
  packages/vcvrack-chemical-elements/PKGBUILD
  packages/vcvrack-dbrack-modules/.gitignore
  packages/vcvrack-dbrack-modules/.nvchecker.toml
  packages/vcvrack-dbrack-modules/PKGBUILD
  packages/vcvrack-quantal-audio/.gitignore
  packages/vcvrack-quantal-audio/.nvchecker.toml
  packages/vcvrack-quantal-audio/PKGBUILD
  packages/vcvrack-wildergarden/.gitignore
  packages/vcvrack-wildergarden/.nvchecker.toml
  packages/vcvrack-wildergarden/PKGBUILD
Labels: package

#553 vcvrack-autinn: add pkgdesc; disable strip
  packages/vcvrack-autinn/PKGBUILD
Labels: enhancement

#554 audiowmark: update to v0.6.4
  packages/audiowmark/PKGBUILD
  packages/audiowmark/audiowmark-configure.patch
  packages/audiowmark/audiowmark-nostdin.patch
  packages/audiowmark/audiowmark-tests.patch
Labels: update
