Repository osam-cologne/archlinux-proaudio, pull requests merged in 2025-01, with the labels that each got.

#511 feat: update package audiowmark to 0.6.3-1
  nvchecker/old_ver.json
  packages/audiowmark/PKGBUILD
  packages/audiowmark/audiowmark-configure.patch
  packages/audiowmark/audiowmark-nostdin.patch
  packages/audiowmark/audiowmark-tests.patch
Labels: update

#516 feat: update package ratatouille.lv2 to 0.9.5-1
  nvchecker/old_ver.json
  packages/ratatouille.lv2/PKGBUILD
Labels: update

#512 vcvrack: fix segfault on wayland
  packages/vcvrack/.install
  packages/vcvrack/PKGBUILD
  packages/vcvrack/vcvrack.sh
  packages/vcvrack/wayland.patch
Labels: bug

#517 feat: update package convertwithmoss to 11.7.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#518 feat: update package abcmidi to 2025.01.04-1
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: update

#519 feat: remove package abcmidi (now in extra)
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/abcmidi/PKGBUILD
Labels: removal

#468 Revert "hack: install previous fakeroot version and ignore future updates"
  .drone.yml
  tools/pacman.conf
Labels: tooling

#520 feat: update package seq66 to 0.99.17.1-1
  nvchecker/old_ver.json
  packages/seq66/PKGBUILD
Labels: update

#522 feat: update package convertwithmoss to 12.0.0-1
  nvchecker/old_ver.json
  packages/convertwithmoss/PKGBUILD
Labels: update

#523 rakarrack-plus: update to v1.2.7
  nvchecker/old_ver.json
  packages/rakarrack-plus/PKGBUILD
Labels: update

#524 feat: add new package 'jack_link'
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/jack_link/PKGBUILD
Labels: package

#525 Add new package 'neural-amp-modeler-lv2'
  aur/packages
  nvchecker/archlinux-proaudio.toml
  nvchecker/old_ver.json
  packages/neural-amp-modeler-lv2/PKGBUILD
Labels: package

#527 Fix group name proaudio → pro-audio for vcvrack plugins
  packages/vcvrack-21khz/PKGBUILD
  packages/vcvrack-8mode/PKGBUILD
  packages/vcvrack-aaronstatic/PKGBUILD
  packages/vcvrack-ahornberg/PKGBUILD
  packages/vcvrack-alefsbits/PKGBUILD
  packages/vcvrack-alikins/PKGBUILD
  packages/vcvrack-alliewayaudio-freebies/PKGBUILD
  packages/vcvrack-amalgamated-harmonics/PKGBUILD
  packages/vcvrack-aridacity/PKGBUILD
  packages/vcvrack-axioma/PKGBUILD
  packages/vcvrack-bastl/PKGBUILD
  packages/vcvrack-collection-one/PKGBUILD
  packages/vcvrack-computerscare/PKGBUILD
  packages/vcvrack-cvly/PKGBUILD
  packages/vcvrack-freesurface/PKGBUILD
  packages/vcvrack-goodsheperd/PKGBUILD
  packages/vcvrack-sonusmodular/PKGBUILD
  packages/vcvrack-zetacarinae/PKGBUILD
  tools/README.md
Labels: enhancement
