Repository osam-cologne/archlinux-proaudio, pull requests merged in 2025-06, with the labels that each got.

#620 vcvrack-venom: update to v2.12.2
  packages/vcvrack-venom/PKGBUILD
Labels: update

#622 Fix nvpr overwriting closed PRs
  nvchecker/nvpr.sh
Labels: tooling

#619 Split package ratatouille
  aur/packages
  packages/ratatouille.lv2/PKGBUILD
  packages/ratatouille/.nvchecker.toml
  packages/ratatouille/PKGBUILD
Labels: package

#628 feat: update package seq66 to 0.99.20-1
  packages/seq66/PKGBUILD
Labels: update

#630 CI: fix SRCDEST on arm64
  .drone.yml
Labels: bug

#470 [octasine] sync to AUR
  aur/packages
  packages/octasine/PKGBUILD
Labels: enhancement

#440 feat: add new package 'pluginval'
  aur/packages
  packages/pluginval/.nvchecker.toml
  packages/pluginval/PKGBUILD
Labels: package

#635 [python-freesimplegui] fix: remove from AUR (already taken)
  aur/packages
  packages/python-freesimplegui/PKGBUILD
Labels: bug
