Repository osam-cologne/archlinux-proaudio, pull requests merged in 2025-04, with the labels that each got.

#575 feat: update package convertwithmoss to 12.2.1-1
  packages/convertwithmoss/PKGBUILD
Labels: update

#576 vcvrack-sicko-cv: update to v2.7.2
  packages/vcvrack-sicko-cv/PKGBUILD
Labels: update

#578 protobuf-21: python split package
  packages/protobuf-21/PKGBUILD
Labels: package

#580 rtcqs: update to v0.6.5
  packages/rtcqs/.gitignore
  packages/rtcqs/.nvchecker.toml
  packages/rtcqs/PKGBUILD
Labels: update

#579 ola: fix python-protobuf dependency
  packages/ola/PKGBUILD
Labels: bug

#581 vcvrack-voxglitch: update to v2.32.4
  packages/vcvrack-voxglitch/PKGBUILD
Labels: update

#582 vcvrack-dbrack-sequencer: update to v2.6.0
  packages/vcvrack-dbrack-sequencer/PKGBUILD
Labels: update

#584 Add new package 'python-qdigitalmeter'
  packages/python-qdigitalmeter/.nvchecker.toml
  packages/python-qdigitalmeter/PKGBUILD
Labels: package

#585 feat: update linux-show-player to 0.6.5-1
  packages/linux-show-player/PKGBUILD
Labels: update

#586 feat: update rtcqs to 0.6.6-1
  packages/rtcqs/PKGBUILD
Labels: update

#588 vcvrack-dbrack-sequencer: update to v2.6.1
  packages/vcvrack-dbrack-sequencer/PKGBUILD
Labels: update

#589 vcvrack: update vcvrack-free to v2.6.2
  packages/vcvrack/PKGBUILD
Labels: update

#591 fix: python-protobuf-21 provides python-protobuf
  packages/protobuf-21/PKGBUILD
Labels: bug

#592 vcvrack-pitchgrid: update to v2.2.0
  packages/vcvrack-pitchgrid/PKGBUILD
Labels: update

#593 vcvrack-sicko-cv: update to v2.7.3
  packages/vcvrack-sicko-cv/PKGBUILD
Labels: update

#594 Fix matrix notification on failure
  .drone.yml
Labels: tooling

#595 octasine: disable LTO to fix missing symbol
  packages/octasine/PKGBUILD
Labels: bug

#597 Speed up some makepkg checks
  tools/clean-build-all.sh
  tools/compare-checksums.sh
  tools/diff-packages.sh
  tools/gen-packagelist.sh
  tools/prepare-build.sh
  tools/push-aur.sh
  tools/syncdeps-all.sh
Labels: tooling

#598 Setup basic shared cache
  .drone.yml
  tools/build-env.sh
  tools/prepare-build.sh
Labels: tooling

#599 convertwithmoss: update to v12.2.2
  packages/convertwithmoss/PKGBUILD
Labels: update

#600 Remove arm64 restriction
  .drone.yml
Labels: tooling

#601 vcvrack-cella: update to v2.8.0
  packages/vcvrack-cella/PKGBUILD
Labels: update

#602 Update vcvrack plugins
  packages/vcvrack-4ms/PKGBUILD
  packages/vcvrack-cella/PKGBUILD
Labels: update
